//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Electronic_Store.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class customer
    {
        public int id { get; set; }
        //[Required(ErrorMessage = "Fullname is required.")]
        public string fullname { get; set; }
        //[Required(ErrorMessage = "Email is required.")]
        //[EmailAddress(ErrorMessage = "Invalid Email Address")]
        public string email { get; set; }
        //[Required(ErrorMessage = "Password is required.")]
        public string password { get; set; }
        public bool status { get; set; }
        //[Compare("password", ErrorMessage = "Confirm password doesn't match, Type again !")]
        public string confirmpassword { get; set; }
    }
}
