//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Electronic_Store.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class upload_images
    {
        public int id { get; set; }
        public string url_images { get; set; }
        public bool status { get; set; }
        public int product_id { get; set; }
    
        public virtual product product { get; set; }
    }
}
